import { RecipeCardInfo } from '../Types/recipe-info';

export const recipesMock: RecipeCardInfo[] = [
  {
    id: 1,
    name: 'Recipe 1',
    time: '30 minutes',
    foodType: 'Meat',
    difficulty: 'Easy',
  },
  {
    id: 2,
    name: 'Recipe 2',
    time: '1 hour',
    foodType: 'Fish',
    difficulty: 'Medium',
  },
  {
    id: 3,
    name: 'Recipe 3',
    time: '2 hours',
    foodType: 'Dairy',
    difficulty: 'Hard',
  },
  {
    id: 4,
    name: 'Recipe 4',
    time: '30 minutes',
    foodType: 'Meat',
    difficulty: 'Easy',
  },
  {
    id: 5,
    name: 'Recipe 5',
    time: '1 hour',
    foodType: 'Fish',
    difficulty: 'Medium',
  },
  {
    id: 6,
    name: 'Recipe 6',
    time: '2 hours',
    foodType: 'Dairy',
    difficulty: 'Hard',
  },
  {
    id: 7,
    name: 'Recipe 7',
    time: '30 minutes',
    foodType: 'Meat',
    difficulty: 'Easy',
  },
  {
    id: 8,
    name: 'Recipe 8',
    time: '1 hour',
    foodType: 'Fish',
    difficulty: 'Medium',
  },
  {
    id: 9,
    name: 'Recipe 9',
    time: '2 hours',
    foodType: 'Dairy',
    difficulty: 'Hard',
  },
  {
    id: 10,
    name: 'Recipe 10',
    time: '30 minutes',
    foodType: 'Meat',
    difficulty: 'Easy',
  },
  {
    id: 11,
    name: 'Recipe 11',
    time: '1 hour',
    foodType: 'Fish',
    difficulty: 'Medium',
  },
  {
    id: 12,
    name: 'Recipe 12',
    time: '2 hours',
    foodType: 'Dairy',
    difficulty: 'Hard',
  },
  {
    id: 13,
    name: 'Recipe 13',
    time: '30 minutes',
    foodType: 'Meat',
    difficulty: 'Easy',
  },
];
